# Generated by Django 4.0.6 on 2022-12-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=3000, null=True)),
                ('dateCreated', models.DateField(auto_now_add=True)),
                ('file', models.FileField(max_length=100000, upload_to='blog')),
                ('poster', models.ImageField(max_length=10000, upload_to='blogPoster')),
            ],
        ),
        migrations.CreateModel(
            name='blogLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=3000, null=True)),
                ('urlsLink', models.URLField(blank=True, max_length=500000, null=True)),
            ],
        ),
    ]
