# Generated by Django 4.0.6 on 2022-12-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetail',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
