# Generated by Django 4.0.6 on 2022-12-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_blogdetail_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetail',
            name='category',
            field=models.CharField(blank=True, choices=[('twitter', 'twitter'), ('comedy', 'comedy'), ('movies', 'movies'), ('facebook', 'facebook'), ('sport', 'sport'), ('entertainment', 'entertainment')], max_length=50, null=True),
        ),
    ]
