# Generated by Django 4.0.6 on 2022-12-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_blogdetail_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetail',
            name='category',
            field=models.CharField(blank=True, choices=[('website', 'website'), ('facebook', 'facebook'), ('twitter', 'twitter'), ('jobs', 'jobs'), ('movies', 'movies'), ('websitesale', 'websitesale'), ('hacked app', 'hackedapk'), ('books', 'books'), ('lovedvideo', 'lovedvideo'), ('news', 'news'), ('comedy', 'comedy'), ('entertainment', 'entertainment'), ('fashion', 'fashion'), ('sport', 'sport'), ('insparitional', 'insparitional'), ('music', 'music')], max_length=50, null=True),
        ),
    ]
