# Generated by Django 4.0.6 on 2022-12-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_blogdetail_like_alter_blogdetail_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetail',
            name='category',
            field=models.CharField(blank=True, choices=[('entertainment', 'entertainment'), ('comedy', 'comedy'), ('website', 'website'), ('movies', 'movies'), ('sport', 'sport'), ('fashion', 'fashion'), ('jobs', 'jobs'), ('news', 'news'), ('music', 'music'), ('hacked app', 'hackedapk'), ('twitter', 'twitter'), ('books', 'books'), ('facebook', 'facebook'), ('insparitional', 'insparitional'), ('lovedvideo', 'lovedvideo'), ('websitesale', 'websitesale')], max_length=50, null=True),
        ),
    ]
