# Generated by Django 4.0.6 on 2022-12-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_blogdetail_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdetail',
            name='poster',
        ),
        migrations.AlterField(
            model_name='blogdetail',
            name='category',
            field=models.CharField(blank=True, choices=[('comedy', 'comedy'), ('books', 'books'), ('website', 'website'), ('facebook', 'facebook'), ('hacked app', 'hackedapk'), ('lovedvideo', 'lovedvideo'), ('websitesale', 'websitesale'), ('entertainment', 'entertainment'), ('jobs', 'jobs'), ('music', 'music'), ('news', 'news'), ('sport', 'sport'), ('twitter', 'twitter'), ('fashion', 'fashion'), ('insparitional', 'insparitional'), ('movies', 'movies')], max_length=50, null=True),
        ),
    ]
