# Generated by Django 4.0.6 on 2022-12-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_blogdetail_file_blogdetail_imgae_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetail',
            name='isItIMg',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='blogdetail',
            name='category',
            field=models.CharField(blank=True, choices=[('comedy', 'comedy'), ('books', 'books'), ('news', 'news'), ('sport', 'sport'), ('jobs', 'jobs'), ('twitter', 'twitter'), ('hacked app', 'hackedapk'), ('entertainment', 'entertainment'), ('movies', 'movies'), ('facebook', 'facebook'), ('websitesale', 'websitesale'), ('website', 'website'), ('lovedvideo', 'lovedvideo'), ('music', 'music'), ('fashion', 'fashion'), ('insparitional', 'insparitional')], max_length=50, null=True),
        ),
    ]
