# Generated by Django 4.0.6 on 2022-12-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_blogdetail_isitimg_alter_blogdetail_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetail',
            name='category',
            field=models.CharField(blank=True, choices=[('music', 'music'), ('jobs', 'jobs'), ('comedy', 'comedy'), ('websitesale', 'websitesale'), ('books', 'books'), ('insparitional', 'insparitional'), ('entertainment', 'entertainment'), ('fashion', 'fashion'), ('facebook', 'facebook'), ('sport', 'sport'), ('hacked app', 'hackedapk'), ('lovedvideo', 'lovedvideo'), ('website', 'website'), ('twitter', 'twitter'), ('movies', 'movies'), ('news', 'news')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='blogdetail',
            name='imgae',
            field=models.ImageField(blank=True, max_length=100000, null=True, upload_to='image'),
        ),
    ]
