# Generated by Django 4.0.6 on 2022-12-11 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_blogdetail_category_alter_blogdetail_imgae_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloglink',
            old_name='urlsLink',
            new_name='facebook',
        ),
        migrations.RemoveField(
            model_name='blogdetail',
            name='isItIMg',
        ),
        migrations.RemoveField(
            model_name='bloglink',
            name='name',
        ),
        migrations.AddField(
            model_name='blogdetail',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.bloglink'),
        ),
        migrations.AddField(
            model_name='bloglink',
            name='instragram',
            field=models.URLField(blank=True, max_length=500000, null=True),
        ),
        migrations.AddField(
            model_name='bloglink',
            name='twitter',
            field=models.URLField(blank=True, max_length=500000, null=True),
        ),
        migrations.AddField(
            model_name='bloglink',
            name='youtube',
            field=models.URLField(blank=True, max_length=500000, null=True),
        ),
        migrations.AlterField(
            model_name='blogdetail',
            name='category',
            field=models.CharField(blank=True, choices=[('sport', 'sport'), ('movies', 'movies'), ('fashion', 'fashion'), ('insparitional', 'insparitional'), ('comedy', 'comedy'), ('facebook', 'facebook'), ('website', 'website'), ('music', 'music'), ('jobs', 'jobs'), ('news', 'news'), ('books', 'books'), ('lovedvideo', 'lovedvideo'), ('hacked app', 'hackedapk'), ('twitter', 'twitter'), ('entertainment', 'entertainment'), ('websitesale', 'websitesale')], max_length=50, null=True),
        ),
    ]
