# Generated by Django 4.0.6 on 2022-12-11 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_urlslink_bloglink_facebook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdetail',
            name='link',
        ),
        migrations.AddField(
            model_name='blogdetail',
            name='facebook',
            field=models.URLField(blank=True, max_length=500000, null=True),
        ),
        migrations.AddField(
            model_name='blogdetail',
            name='instragram',
            field=models.URLField(blank=True, max_length=500000, null=True),
        ),
        migrations.AddField(
            model_name='blogdetail',
            name='twitter',
            field=models.URLField(blank=True, max_length=500000, null=True),
        ),
        migrations.AddField(
            model_name='blogdetail',
            name='youtube',
            field=models.URLField(blank=True, max_length=500000, null=True),
        ),
        migrations.AlterField(
            model_name='blogdetail',
            name='category',
            field=models.CharField(blank=True, choices=[('fashion', 'fashion'), ('news', 'news'), ('sport', 'sport'), ('entertainment', 'entertainment'), ('jobs', 'jobs'), ('website', 'website'), ('music', 'music'), ('facebook', 'facebook'), ('movies', 'movies'), ('twitter', 'twitter'), ('websitesale', 'websitesale'), ('lovedvideo', 'lovedvideo'), ('comedy', 'comedy'), ('hacked app', 'hackedapk'), ('insparitional', 'insparitional'), ('books', 'books')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='blogLink',
        ),
    ]
