# Generated by Django 4.0.6 on 2022-12-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_blogdetail_link_blogdetail_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetail',
            name='whatsapp',
            field=models.URLField(blank=True, max_length=500000, null=True),
        ),
        migrations.AlterField(
            model_name='blogdetail',
            name='category',
            field=models.CharField(blank=True, choices=[('lovedvideo', 'lovedvideo'), ('websitesale', 'websitesale'), ('comedy', 'comedy'), ('twitter', 'twitter'), ('sport', 'sport'), ('books', 'books'), ('music', 'music'), ('news', 'news'), ('entertainment', 'entertainment'), ('jobs', 'jobs'), ('fashion', 'fashion'), ('movies', 'movies'), ('insparitional', 'insparitional'), ('hacked app', 'hackedapk'), ('facebook', 'facebook'), ('website', 'website')], max_length=50, null=True),
        ),
    ]
